node {
  echo "test ENV"
  echo "BRANCH_NAME'${env.BRANCH_NAME}'"
  echo "CHANGE_ID'${env.CHANGE_ID}'"
  echo "CHANGE_URL'${env.CHANGE_URL}'"
  echo "CHANGE_TITLE'${env.CHANGE_TITLE}'"
  echo "CHANGE_AUTHOR'${env.CHANGE_AUTHOR}'"
  echo "CHANGE_AUTHOR_DISPLAY_NAME'${env.CHANGE_AUTHOR_DISPLAY_NAME}'"
  echo "CHANGE_AUTHOR_EMAIL'${env.CHANGE_AUTHOR_EMAIL}'"
  echo "CHANGE_TARGET'${env.CHANGE_TARGET}'"
  echo "BUILD_NUMBER'${env.BUILD_NUMBER}'"
}
